version: '3'
services:
  app:
    build: ./src/frontend
    restart: always
    ports:
      - '80:80'
  api:
    build: ./src/api
    restart: always
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - '3000:3000'
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=kneipenliga
      - DATABASE_HOST=0.0.0.0
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
    driver: local
